version: '3.8'
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        
        restart: always

        # environment:
        #     DATABASE_URL : postgres://postgres:ankur@123@postgres:5432/postgres
        #     NODE_ENV : development
        #     PORT: 3002

        ports: 
           -  "5000:3002"

    graphql-engine:
        image: hasura/graphql-engine:v2.0.1
        ports:
        - "8080:8080"

        # environment:
        #   HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:ankur@123@postgres:5432/postgres
        #   HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
        #   HASURA_GRAPHQL_DEV_MODE: "true"
        #   HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log


    postgres:

        image: postgres:14.1
        ports:
            - "5001:5432"

        environment: 
           POSTGRES_USER : postgres
           POSTGRES_PASSWORD : ankur@123
           POSTGRES_DB : postgres

