version: '3.8'
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        
        restart: always

        enviorment:
            DATABASE_URL : postgres://postgres:ankur.p@solutelabs.com@postgres:3000/db
            NODE_ENV : development
            PORT: 3002

        ports: 
           -  "8080:3002"

    graphql-engine:
    image: hasura/graphql-engine:v2.0.0
    ports:
      - "8080:8080"
      

    postgres:

        image: postgres:14.1
        ports:
            - "5432:3000"

        enviorment: 
           DB_USER : postgres
           DB_PASS : ankur.p@solutelabs.com
           POSTGRES_DB : db
           volumes:
            - db_data:/var/lib/postgresql/data

